### ISSUE TITLE
Update instructions on how to run awx-manage

### ISSUE THREAD

**Issue by cbolz** [ansible-labs-crew/ansible-labs-summit2021#20] opened 2021-09-14 07:54 UTC
Lab guide currently runs this on bastion, but that won't work. Instructions need to be updated to log into controller and run `awx-manage` from there.

**Comment by ericzolf** [comment] 2021-09-14 08:54
Isn't it a duplicate of #17 ?

**Comment by cbolz** [comment] 2021-09-14 08:57
it is

**Closed as completed** 2021-09-14 09:10 UTC
